# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmdpeek" do
  version "0.0.8"

  on_macos do
    on_intel do
      sha256 "12a6273558f652f334f73fc37da272177891d798d5c83103a001da811e660ccc"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea563619b86284046fa9e3c03be4c7a27be0dc255c5d73d7590feb1008e1d163"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74f12cbc2837351f796534b8fea552bc6688a8777bce3b5bf07675b88d5a956b"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "613d3733b0d2924748a7a86e28ba8ac97f43ca4e7d1f355de509d84e8f55caf7"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "cmdpeek"
  desc "Searchable interactive command palette for reusable terminal workflows"
  homepage "https://github.com/pierinho13/cmdpeek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmdpeek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/cmdpeek"
        ]
    end
  end

  # No zap stanza required

end
