# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmdpeek" do
  version "0.0.13"

  on_macos do
    on_intel do
      sha256 "fdca20b19c5a9cea7f71c8dbd33e92266b5fca79c5512c11d5e12443f44235a6"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3172adc9347bd33c659848e1ec77e4959451828c4308e407f5168d18544f2e7b"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "db27103c0038a54809d8b3e43b2b13ffd210f844a529b07abfd38ccc219b7f54"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44b65f21f8f04a513eba2ded90b21d635c1537485acacf2488515297c9ce821b"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "cmdpeek"
  desc "Searchable interactive command palette for reusable terminal workflows"
  homepage "https://github.com/pierinho13/cmdpeek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmdpeek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/cmdpeek"
        ]
    end
  end

  # No zap stanza required

end
