# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmdpeek" do
  version "0.0.12"

  on_macos do
    on_intel do
      sha256 "3d6a42bbaacac102123c66bd33719c75d43f981bfde8d464d096fa8eecf10274"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d6350b0ff3341743eb48fe2868e8f2e1b67c7684047534f138bf391e284efce"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "37b847ae3e6d05e9b336f0258e6ca42f3763971d639631347a5e5bdbeba404ef"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b8d7d488dd191355d72cdd6352b9c37a6541a20b26fedb7bd6a30dcbfe9fac5"
      url "https://github.com/pierinho13/cmdpeek/releases/download/v#{version}/cmdpeek_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "cmdpeek"
  desc "Searchable interactive command palette for reusable terminal workflows"
  homepage "https://github.com/pierinho13/cmdpeek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cmdpeek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/cmdpeek"
        ]
    end
  end

  # No zap stanza required

end
