# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-peek" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "6636f50d263215f67189f351ec70d07ae831ec777af4a180ea7d0a329fc4737b"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1e8e41d5ec5e4a96a0a03b05f9fc664b45b28b36f3e9c98dffedff81caae003"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7c7f80e8b5bf2b68b204d8ce7d3b3892f9bb7790df9a7516a0b3b9fde08a68b"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c61a7728adbad926823a5e5c0b986f2d8fc4ce42144d48006f78958023f053a"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kubectl-peek"
  desc "Simple interactive kubectl plugin for browsing Secrets and discovering where they are used"
  homepage "https://github.com/pierinho13/kubectl-peek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-peek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/kubectl-peek"
        ]
    end
  end

  # No zap stanza required

end
