# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-peek" do
  version "0.1.18"

  on_macos do
    on_intel do
      sha256 "2d09a8753adc5fb5ce45e6a9cbe0bd3083c838a2cc734bdfd9ce04974d6eb2b4"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f81040a4aa03c74c57c39705b6a57003335a708a55d524817f32737453ef7254"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b0b9dd53734f8229886211049d28869ff13dafe98bbfe3c40ac64d8fe7f01b8"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d95af782bcd3aa80d32952823ba19e62ae1c52923b75706082f2bc15fa24637"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kubectl-peek"
  desc "Simple interactive kubectl plugin for browsing Secrets and discovering where they are used"
  homepage "https://github.com/pierinho13/kubectl-peek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-peek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/kubectl-peek"
        ]
    end
  end

  # No zap stanza required

end
