# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-peek" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "b79e14fbc41c019e52034134a13edaea17fe1fe6843992ddac9090816a734e5f"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac27a9df59346bf212af4633709336e3db55958ca56259cf11774cc98f376b0f"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0fe629e50a84239ebe0e758614baafc8be68b8a0e98ad99916005686684a78a"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "124d9c316320a9c676ca20b2bac1345825558650efcceb7efc8e550b2137e610"
      url "https://github.com/pierinho13/kubectl-peek/releases/download/v#{version}/kubectl-peek_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "kubectl-peek"
  desc "Interactive CLI for browsing and decoding Kubernetes Secrets"
  homepage "https://github.com/pierinho13/kubectl-peek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-peek"

  # No zap stanza required

end
